; AUTOMATICLY GENERATED BY NEMET COMPILER
; NEMET v0.0.1-Beta COPYRIGHT MAHANFARZANEH 2023-2024
section .text
global main
extern printf

main:
    mov eax, 1
    imul eax, 2
    push eax
    push message
    call printf
    add esp, 8
    ret
    
message db "register = %08X", 10, 0
